---

- name: Checkout openHAB Cloud
  ansible.builtin.git:
    repo: "{{ openhabcloud_repository }}"
    dest: "{{ openhabcloud_base_path }}"
    version: "{{ openhabcloud_repository_branch }}"
    single_branch: yes
    force: yes

- name: Ensure openHAB Cloud path is added as git safe directory
  ansible.builtin.command: git config --global --add safe.directory {{ openhabcloud_base_path }}
  check_mode: no

- name: Change openHAB Cloud folder ownership
  ansible.builtin.file:
    dest: "{{ openhabcloud_base_path }}"
    owner: "{{ openhabcloud_uid }}"
    group: "{{ openhabcloud_gid }}"
    recurse: yes

- name: Ensure openHAB Cloud docker-composeand config.json files are created
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "{{ openhabcloud_base_path }}/deployment/docker-compose/{{ item }}"
    mode: "0640"
    owner: "{{ openhabcloud_uid }}"
    group: "{{ openhabcloud_gid }}"
  with_items:
    - docker-compose.yml
    - config.json

- name: Ensure openHAB Cloud docker image is build
  ansible.builtin.command:
    cmd: "{{ devture_systemd_docker_base_host_command_docker }} compose build"
    chdir: "{{ openhabcloud_base_path }}/deployment/docker-compose"

- name: Ensure openHAB Cloud container network is created
  community.general.docker_network:
    name: "{{ openhabcloud_container_network }}"
    driver: bridge

- name: Ensure openHAB Cloud systemd service installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/openhab-cloud.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ openhabcloud_identifier }}.service"
    mode: "0644"
