---

- name: Ensure openHAB Cloud paths exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
    owner: "{{ openhab_cloud_uid }}"
    group: "{{ openhab_cloud_gid }}"
  with_items:
    - "{{ openhab_cloud_base_path }}"
    - "{{ openhab_cloud_source_path }}"
    - "{{ openhab_cloud_config_path }}"
    - "{{ openhab_cloud_log_path }}"

- name: Ensure openHAB Cloud source path is added as git safe directory
  ansible.builtin.command: git config --global --add safe.directory {{ openhab_cloud_source_path }}
  check_mode: no

- name: Checkout openHAB Cloud
  ansible.builtin.git:
    repo: "{{ openhab_cloud_repository }}"
    dest: "{{ openhab_cloud_source_path }}"
    version: "{{ openhab_cloud_repository_branch }}"
    single_branch: yes
    depth: 1
    force: yes

- name: Change openHAB Cloud source folder ownership
  ansible.builtin.file:
    dest: "{{ openhab_cloud_source_path }}"
    owner: "{{ openhab_cloud_uid }}"
    group: "{{ openhab_cloud_gid }}"
    recurse: yes

- name: Ensure openHAB Cloud config.json file is created
  ansible.builtin.template:
    src: "{{ role_path }}/templates/config.json.j2"
    dest: "{{ openhab_cloud_config_path }}/config.json"
    mode: "0644"
    owner: "{{ openhab_cloud_uid }}"
    group: "{{ openhab_cloud_gid }}"

- name: Remove openHAB Cloud image
  community.docker.docker_image:
    name: "{{ openhab_cloud_container_image }}"
    state: absent

- name: Ensure openHAB Cloud image is build
  community.docker.docker_image_build:
    name: "{{ openhab_cloud_container_image }}"
    path: "{{ openhab_cloud_source_path }}"
  register: result
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: result is not failed

- name: Ensure openHAB Cloud container network is created
  community.general.docker_network:
    name: "{{ openhab_cloud_container_network }}"
    driver: bridge
    driver_options: "{{ devture_systemd_docker_base_container_networks_driver_options }}"

- name: Ensure openHAB Cloud systemd service installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/openhab-cloud.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ openhab_cloud_identifier }}.service"
    mode: "0644"
