---

- tags:
    - setup-all
    - setup-openhabcloud
    - install-all
    - install-openhabcloud
  block:
    - when: openhab_cloud_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - when: openhab_cloud_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- tags:
    - setup-all
    - setup-openhabcloud
  block:
    - when: not openhab_cloud_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
