---

- name: Check existence of openHAB Cloud systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ openhab_cloud_identifier }}.service"
  register: openhab_cloud_service_stat

- when: openhab_cloud_service_stat.stat.exists | bool
  block:
    - name: Ensure openHAB Cloud is stopped
      ansible.builtin.service:
        name: "{{ openhab_cloud_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure openHAB Cloud systemd service doesn't exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ openhab_cloud_identifier }}"
        state: absent

    - name: Ensure openhabcloud base path doesn't exist
      ansible.builtin.file:
        path: "{{ openhab_cloud_base_path }}"
        state: absent
