---

- name: (Deprecation) Catch and report renamed openhabcloud settings
  ansible.builtin.fail:
    msg: >-
      Your configuration contains a variable, which now has a different name.
      Please change your configuration to rename the variable (`{{ item.old }}` -> `{{ item.new }}`).
  when: "item.old in vars"
  with_items:
    - {'old': 'openhabcloud_container_additional_networks_additional', 'new': 'openhabcloud_container_additional_networks_custom'}

- name: Fail if required openhabcloud settings not defined
  ansible.builtin.fail:
    msg: >
      You need to define a required configuration setting (`{{ item }}`).
  when: "vars[item] == ''"
  with_items:
    - openhabcloud_identifier
    - openhabcloud_uid
    - openhabcloud_gid
    - openhabcloud_domain_name
    - openhabcloud_container_network
