---

- name: Fail if required openHAB Cloud settings not defined
  ansible.builtin.fail:
    msg: >
      You need to define a required configuration setting (`{{ item }}`).
  when: "vars[item] == ''"
  with_items:
    - openhab_cloud_identifier
    - openhab_cloud_uid
    - openhab_cloud_gid
    - openhab_cloud_domain_name
    - openhab_cloud_container_network
